version: '3.8'

services:

  frontend:
      build:
        context: ./money-calculator-front
        dockerfile: Dockerfile
      ports:
        - "3000:80"
        
  backend:
    build:
      context: ./money-calculator-back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:mysql://sql7.freemysqlhosting.net:3306/sql7748733?serverTimezone=UTC
      - DATABASE_USERNAME=sql7748733
      - DATABASE_PWD=24Kijg5kuS
      - FRONTEND_URL=http://localhost:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge